#!/usr/bin/env python3
"""Generate and validate LVGL true-color-alpha image arrays from PNG assets."""

from __future__ import annotations

import argparse
import glob
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

try:
    from PIL import Image
except ImportError as error:
    raise SystemExit("Pillow is required: python -m pip install Pillow") from error


ROOT = Path(__file__).resolve().parents[1]
ASSET_DIR = ROOT / "apps" / "lens_react_ui" / "assets"
DEFAULT_MANIFEST = ASSET_DIR / "assets.json"


@dataclass(frozen=True)
class ConvertedImage:
    symbol: str
    width: int
    height: int
    bgra: bytes


def load_manifest(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as manifest_file:
        manifest = json.load(manifest_file)
    if manifest.get("schema") != 2:
        raise ValueError(f"Unsupported asset manifest schema: {manifest.get('schema')}")
    return manifest


def source_paths(pattern: str) -> list[Path]:
    return sorted(Path(item) for item in glob.glob(str(ASSET_DIR / pattern)))


def symbol_for(group: dict, source: Path, source_count: int) -> str:
    explicit = group.get("symbol")
    if explicit:
        if source_count != 1:
            raise ValueError(f"{group['id']}: explicit symbol requires exactly one source")
        return explicit
    return f"{source.stem}{group.get('symbol_suffix', '')}"


def convert_png(source: Path, symbol: str) -> ConvertedImage:
    with Image.open(source) as image:
        rgba_image = image.convert("RGBA")
        rgba = rgba_image.tobytes()
        bgra = bytearray(len(rgba))
        for index in range(0, len(rgba), 4):
            red, green, blue, alpha = rgba[index:index + 4]
            bgra[index:index + 4] = bytes((blue, green, red, alpha))
        return ConvertedImage(symbol, rgba_image.width, rgba_image.height, bytes(bgra))


def converted_groups(manifest: dict, manifest_path: Path) -> dict[Path, list[ConvertedImage]]:
    generated_dir = (manifest_path.parent / manifest["generated_c_directory"]).resolve()
    groups: dict[Path, list[ConvertedImage]] = {}
    for group in manifest["asset_groups"]:
        sources = source_paths(group["source"])
        if not sources:
            raise ValueError(f"{group['id']}: no source matched {group['source']}")
        output = (generated_dir / group["output"]).resolve()
        if not output.is_relative_to(generated_dir):
            raise ValueError(f"{group['id']}: output escapes generated directory")
        converted = [convert_png(source, symbol_for(group, source, len(sources))) for source in sources]
        symbols = [image.symbol for image in converted]
        if len(symbols) != len(set(symbols)):
            raise ValueError(f"{group['id']}: duplicate generated symbols")
        groups[output] = converted
    return groups


def format_bytes(data: bytes) -> Iterable[str]:
    for offset in range(0, len(data), 16):
        values = ", ".join(f"0x{value:02x}" for value in data[offset:offset + 16])
        yield f"    {values},"


def render_output(images: list[ConvertedImage]) -> str:
    lines = [
        "/* Generated by tools/generate_lens_assets.py. Do not edit manually. */",
        '#include "lvgl.h"',
        "#ifndef LV_ATTRIBUTE_MEM_ALIGN",
        "#define LV_ATTRIBUTE_MEM_ALIGN",
        "#endif",
        "#ifndef LV_ATTRIBUTE_LARGE_CONST",
        "#define LV_ATTRIBUTE_LARGE_CONST",
        "#endif",
        "",
    ]
    for image in images:
        lines.append(
            f"const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST uint8_t {image.symbol}_map[] = {{"
        )
        lines.extend(format_bytes(image.bgra))
        lines.extend([
            "};",
            "",
            f"const lv_img_dsc_t {image.symbol} = {{",
            "    .header.always_zero = 0,",
            "    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,",
            f"    .header.w = {image.width},",
            f"    .header.h = {image.height},",
            f"    .data_size = {len(image.bgra)},",
            f"    .data = {image.symbol}_map,",
            "};",
            "",
        ])
    return "\n".join(lines)


def parse_generated(path: Path) -> dict[str, ConvertedImage]:
    text = path.read_text(encoding="utf-8")
    maps = {
        symbol: bytes(int(value, 16) for value in re.findall(r"0x([0-9a-fA-F]{2})", body))
        for symbol, body in re.findall(r"([A-Za-z_][A-Za-z0-9_]*)_map\[\]\s*=\s*\{(.*?)\};", text, re.S)
    }
    parsed: dict[str, ConvertedImage] = {}
    descriptor_pattern = re.compile(
        r"const\s+lv_img_dsc_t\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*\{(.*?)\};", re.S
    )
    for symbol, body in descriptor_pattern.findall(text):
        width_match = re.search(r"\.header\.w\s*=\s*(\d+)", body)
        height_match = re.search(r"\.header\.h\s*=\s*(\d+)", body)
        if width_match and height_match and symbol in maps:
            parsed[symbol] = ConvertedImage(
                symbol,
                int(width_match.group(1)),
                int(height_match.group(1)),
                maps[symbol],
            )
    return parsed


def check_outputs(
    groups: dict[Path, list[ConvertedImage]], generated_dir: Path, check_unmanaged: bool = True
) -> list[str]:
    errors: list[str] = []
    expected_outputs = set(groups)
    for output, expected_images in groups.items():
        if not output.exists():
            errors.append(f"missing generated output: {output.relative_to(ROOT)}")
            continue
        actual = parse_generated(output)
        expected = {image.symbol: image for image in expected_images}
        if actual.keys() != expected.keys():
            errors.append(f"symbol mismatch: {output.relative_to(ROOT)}")
            continue
        for symbol, expected_image in expected.items():
            if actual[symbol] != expected_image:
                errors.append(f"pixel or size mismatch: {output.relative_to(ROOT)}:{symbol}")

    if check_unmanaged:
        for category in ("ui", "simulation"):
            category_dir = generated_dir / category
            if not category_dir.exists():
                continue
            for output in category_dir.glob("*.c"):
                if output.resolve() not in expected_outputs:
                    errors.append(f"unmanaged generated output: {output.relative_to(ROOT)}")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--check", action="store_true", help="validate without writing files")
    parser.add_argument("--group", action="append", help="generate only the selected asset group id")
    args = parser.parse_args()

    manifest_path = args.manifest.resolve()
    try:
        manifest = load_manifest(manifest_path)
        if args.group:
            selected = set(args.group)
            available = {group["id"] for group in manifest["asset_groups"]}
            unknown = selected - available
            if unknown:
                raise ValueError(f"unknown asset groups: {', '.join(sorted(unknown))}")
            manifest["asset_groups"] = [
                group for group in manifest["asset_groups"] if group["id"] in selected
            ]
        groups = converted_groups(manifest, manifest_path)
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1

    generated_dir = (manifest_path.parent / manifest["generated_c_directory"]).resolve()
    if args.check:
        errors = check_outputs(groups, generated_dir, check_unmanaged=not args.group)
        for error in errors:
            print(f"ERROR: {error}")
        if errors:
            return 1
        print(f"Lens image assets are synchronized ({sum(map(len, groups.values()))} images).")
        return 0

    for output, images in groups.items():
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(render_output(images), encoding="utf-8", newline="\n")
        print(f"Generated {output.relative_to(ROOT)} ({len(images)} images)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
